### PR TITLE
Fixes some issues

### LINKED ISSUE #2: Allow a subdomain with more levels
Currently cannot add domains like: test.test.test.me.

### PR DESCRIPTION
**Pull request by espensgr**
Fixes #2 #3 #5

### CODE REVIEW

**Comment by espensgr** [comment]
Tested the repo so just added som of the fixes and TVDB support

File: js/content-scripts/tvdb.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
+let overseerrContainer, imdbId, tmdbId, mediaType, mediaInfo;
+
+containerOptions.anchorElement = '#translations';
+containerOptions.containerClass = 'mb-2 py-2';
+containerOptions.badgeBackground = '#313131';
+
+const imdbRegex = /\/title\/(tt\d+)(?:\/|$).*/;
+
+mediaType = document.location.pathname.startsWith('/movies') ? 'movie' : 'tv';
+let matches = $("a[href*='/title/tt']", $('#series_basic_info')).attr( "href" ).match(imdbRegex);
```
Comment (RemiRigal) [inline js/content-scripts/tvdb.js:10]: Overseerr relies on the TMDB id for its content. Here you are collecting the IMDb id but your are not using it.
In the `On other sites` section of TVDB you actually have a direct link to the TMDB page and can therefore use this link to get the TMDB id and directly call the `queryMedia` function, instead of searching the media based on the title first.
Could you edit this script to do so ?

File: js/content-scripts/tvdb.js [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+    insertSpinner();
+
+    pullStoredData(function () {
+        if (!userId) {
+            removeSpinner();
+            insertNotLoggedInButton();
+            return;
+        }
+
+        chrome.runtime.sendMessage({contentScriptQuery: 'search', title: title}, json => {
```
Comment (RemiRigal) [inline js/content-scripts/tvdb.js:29]: This call can be avoided, and should be since we can retrieve the TMDB id directly, see previous comment.

**Review by RemiRigal — CHANGES_REQUESTED** [review]
Hi @espensgr ! First, thanks a lot for taking the time to improve this extension.
Your improvements for the settings validation are perfect.
The TVDB integration could be improved, see my detailed comments. Can you take care of that ?

**Comment by espensgr** [comment]
I will do some extra checks, but not all of the movies/series have the TMBD id, so thats why i use the IMDB id if it is there.
So i will check if TMBD is there or else it will run the current setup.

**Comment by espensgr** [comment]
Did a few more enhancements and "fixes"

**Review by RemiRigal — APPROVED** [review]

**Comment by RemiRigal** [comment]
Awesome, thank you for your work on this, I appreicate it. Your improvements on `imdb.js` are also welcome, it's definitely better now !
The new version should be available soon in the store.
